[default]
DEBUG = false
FLASK_ADMIN_NAME = "Gisela Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
FLASK_ADMIN_TITLE = "Gisela Ortt"
EXTENSIONS = [
    "app.site.pages:init_app",
    "app.site.ilustrations:init_app",
    "app.site.publications:init_app",
    "app.hooks:init_app",
    "app.admin:init_app",
]

[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]
